# Generated by Django 5.0.2 on 2024-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_medicalrecords_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdetails',
            old_name='appointment_Time',
            new_name='appointment_time',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='Address',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='area',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='houseNo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='postalCode',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
